# Generated by Django 4.1.4 on 2023-01-04 07:40

import django.contrib.postgres.fields.citext
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_category_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="name",
            field=django.contrib.postgres.fields.citext.CITextField(
                max_length=255, unique=True
            ),
        ),
    ]
