# Generated by Django 4.1.4 on 2023-01-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_category_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="category",
        ),
        migrations.AddField(
            model_name="blog",
            name="category",
            field=models.ManyToManyField(related_name="categories", to="blog.category"),
        ),
    ]
